[package]
name = "wasm3_run"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm3 = {  git="https://github.com/luyikk/wasm3-rs.git" }
anyhow = "1"